#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
pub enum AppSettingsKey {
    ClipboardRetention,
    ClipboardDisabledApps,
    HyperKey,
    HyperKeyIncludesShift,
    HyperKeyQuickPress,
    EmojiSkinTone,
    PopToRootTimeout,
    Appearance,
    CompactMode,
    ShowFavoritesInCompactMode,
    SearchScopes,
    OpenOnCursorScreen,
    AutoSwitchInputSource,
    PaletteDraggable,
    PalettePosition,
    FileSearchEnabled,
    FileSearchScopes,
    FileSearchIgnorePatterns,
    NotesEnabled,
    CustomCommandsEnabled,
    CustomCommandsShowInLauncher,
    SnippetsEnabled,
    SnippetsShowInLauncher,
    WindowManagementEnabled,
    WindowManagementShowInLauncher,
    WindowGap,
    WindowCycleOnRepeat,
    QuicklinksEnabled,
    QuicklinksShowInLauncher,
    QuicklinkOpensNewWindow,
    QuicklinkSelectionFallback,
    QuicklinkConfirmsBeforeDelete,
    ExtensionsEnabled,
    ExtensionsShowInLauncher,
    ExtensionPackageManager,
    ExtensionRegistries,
    ExtensionCustomSearchPaths,
    CalendarEnabled,
    CalendarShowInLauncher,
    JoinWindowMinutes,
    AutoJoinMeetings,
    AutoJoinConfirms,
    CameraPreview,
    MenuBarEvents,
    MenuBarLinkedEventsOnly,
    HideCurrentEvent,
    AiEnabled,
    AiConnections,
    AiDefaultModel,
    AiWebSearch,
    AiSystemPrompt,
    AiSystemPromptEnabled,
    AiRetention,
    AiOpensTo,
    AiNewChatAfter,
    QuickActionsEnabled,
    QuickActionModel,
    QuickActionPreviews,
    QuickActionLanguage,
    SupportReminders,
}

impl AppSettingsKey {
    pub const ALL: &'static [AppSettingsKey] = &[
        AppSettingsKey::ClipboardRetention,
        AppSettingsKey::ClipboardDisabledApps,
        AppSettingsKey::HyperKey,
        AppSettingsKey::HyperKeyIncludesShift,
        AppSettingsKey::HyperKeyQuickPress,
        AppSettingsKey::EmojiSkinTone,
        AppSettingsKey::PopToRootTimeout,
        AppSettingsKey::Appearance,
        AppSettingsKey::CompactMode,
        AppSettingsKey::ShowFavoritesInCompactMode,
        AppSettingsKey::SearchScopes,
        AppSettingsKey::OpenOnCursorScreen,
        AppSettingsKey::AutoSwitchInputSource,
        AppSettingsKey::PaletteDraggable,
        AppSettingsKey::PalettePosition,
        AppSettingsKey::FileSearchEnabled,
        AppSettingsKey::FileSearchScopes,
        AppSettingsKey::FileSearchIgnorePatterns,
        AppSettingsKey::NotesEnabled,
        AppSettingsKey::CustomCommandsEnabled,
        AppSettingsKey::CustomCommandsShowInLauncher,
        AppSettingsKey::SnippetsEnabled,
        AppSettingsKey::SnippetsShowInLauncher,
        AppSettingsKey::WindowManagementEnabled,
        AppSettingsKey::WindowManagementShowInLauncher,
        AppSettingsKey::WindowGap,
        AppSettingsKey::WindowCycleOnRepeat,
        AppSettingsKey::QuicklinksEnabled,
        AppSettingsKey::QuicklinksShowInLauncher,
        AppSettingsKey::QuicklinkOpensNewWindow,
        AppSettingsKey::QuicklinkSelectionFallback,
        AppSettingsKey::QuicklinkConfirmsBeforeDelete,
        AppSettingsKey::ExtensionsEnabled,
        AppSettingsKey::ExtensionsShowInLauncher,
        AppSettingsKey::ExtensionPackageManager,
        AppSettingsKey::ExtensionRegistries,
        AppSettingsKey::ExtensionCustomSearchPaths,
        AppSettingsKey::CalendarEnabled,
        AppSettingsKey::CalendarShowInLauncher,
        AppSettingsKey::JoinWindowMinutes,
        AppSettingsKey::AutoJoinMeetings,
        AppSettingsKey::AutoJoinConfirms,
        AppSettingsKey::CameraPreview,
        AppSettingsKey::MenuBarEvents,
        AppSettingsKey::MenuBarLinkedEventsOnly,
        AppSettingsKey::HideCurrentEvent,
        AppSettingsKey::AiEnabled,
        AppSettingsKey::AiConnections,
        AppSettingsKey::AiDefaultModel,
        AppSettingsKey::AiWebSearch,
        AppSettingsKey::AiSystemPrompt,
        AppSettingsKey::AiSystemPromptEnabled,
        AppSettingsKey::AiRetention,
        AppSettingsKey::AiOpensTo,
        AppSettingsKey::AiNewChatAfter,
        AppSettingsKey::QuickActionsEnabled,
        AppSettingsKey::QuickActionModel,
        AppSettingsKey::QuickActionPreviews,
        AppSettingsKey::QuickActionLanguage,
        AppSettingsKey::SupportReminders,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            AppSettingsKey::ClipboardRetention => "clipboardRetentionDays",
            AppSettingsKey::ClipboardDisabledApps => "clipboardDisabledApps",
            AppSettingsKey::HyperKey => "hyperKeyPhysicalKey",
            AppSettingsKey::HyperKeyIncludesShift => "hyperKeyIncludesShift",
            AppSettingsKey::HyperKeyQuickPress => "hyperKeyQuickPress",
            AppSettingsKey::EmojiSkinTone => "emojiSkinTone",
            AppSettingsKey::PopToRootTimeout => "popToRootTimeout",
            AppSettingsKey::Appearance => "appearance",
            AppSettingsKey::CompactMode => "compactMode",
            AppSettingsKey::ShowFavoritesInCompactMode => "showFavoritesInCompactMode",
            AppSettingsKey::SearchScopes => "launcherSearchScopes",
            AppSettingsKey::OpenOnCursorScreen => "openOnCursorScreen",
            AppSettingsKey::AutoSwitchInputSource => "autoSwitchInputSource",
            AppSettingsKey::PaletteDraggable => "paletteDraggable",
            AppSettingsKey::PalettePosition => "palettePosition",
            AppSettingsKey::FileSearchEnabled => "fileSearchEnabled",
            AppSettingsKey::FileSearchScopes => "fileSearchScopes",
            AppSettingsKey::FileSearchIgnorePatterns => "fileSearchIgnorePatterns",
            AppSettingsKey::NotesEnabled => "notesEnabled",
            AppSettingsKey::CustomCommandsEnabled => "customCommandsEnabled",
            AppSettingsKey::CustomCommandsShowInLauncher => "customCommandsShowInLauncher",
            AppSettingsKey::SnippetsEnabled => "snippetsEnabled",
            AppSettingsKey::SnippetsShowInLauncher => "snippetsShowInLauncher",
            AppSettingsKey::WindowManagementEnabled => "windowManagementEnabled",
            AppSettingsKey::WindowManagementShowInLauncher => "windowManagementShowInLauncher",
            AppSettingsKey::WindowGap => "windowManagementGap",
            AppSettingsKey::WindowCycleOnRepeat => "windowManagementCycleOnRepeat",
            AppSettingsKey::QuicklinksEnabled => "quicklinksEnabled",
            AppSettingsKey::QuicklinksShowInLauncher => "quicklinksShowInLauncher",
            AppSettingsKey::QuicklinkOpensNewWindow => "quicklinkOpensNewWindow",
            AppSettingsKey::QuicklinkSelectionFallback => "quicklinkSelectionFallback",
            AppSettingsKey::QuicklinkConfirmsBeforeDelete => "quicklinkConfirmsBeforeDelete",
            AppSettingsKey::ExtensionsEnabled => "extensionsEnabled",
            AppSettingsKey::ExtensionsShowInLauncher => "extensionsShowInLauncher",
            AppSettingsKey::ExtensionPackageManager => "extensionPackageManager",
            AppSettingsKey::ExtensionRegistries => "extensionRegistries",
            AppSettingsKey::ExtensionCustomSearchPaths => "extensionCustomSearchPaths",
            AppSettingsKey::CalendarEnabled => "calendarEnabled",
            AppSettingsKey::CalendarShowInLauncher => "calendarShowInLauncher",
            AppSettingsKey::JoinWindowMinutes => "joinWindowMinutes",
            AppSettingsKey::AutoJoinMeetings => "autoJoinMeetings",
            AppSettingsKey::AutoJoinConfirms => "autoJoinConfirms",
            AppSettingsKey::CameraPreview => "cameraPreview",
            AppSettingsKey::MenuBarEvents => "menuBarEvents",
            AppSettingsKey::MenuBarLinkedEventsOnly => "menuBarLinkedEventsOnly",
            AppSettingsKey::HideCurrentEvent => "hideCurrentEvent",
            AppSettingsKey::AiEnabled => "aiEnabled",
            AppSettingsKey::AiConnections => "aiConnections",
            AppSettingsKey::AiDefaultModel => "aiDefaultModel",
            AppSettingsKey::AiWebSearch => "aiWebSearch",
            AppSettingsKey::AiSystemPrompt => "aiSystemPrompt",
            AppSettingsKey::AiSystemPromptEnabled => "aiSystemPromptEnabled",
            AppSettingsKey::AiRetention => "aiRetentionDays",
            AppSettingsKey::AiOpensTo => "aiOpensTo",
            AppSettingsKey::AiNewChatAfter => "aiNewChatAfterMinutes",
            AppSettingsKey::QuickActionsEnabled => "quickActionsEnabled",
            AppSettingsKey::QuickActionModel => "quickActionModel",
            AppSettingsKey::QuickActionPreviews => "quickActionPreviews",
            AppSettingsKey::QuickActionLanguage => "quickActionLanguage",
            AppSettingsKey::SupportReminders => "supportReminders",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn settings_key_raw_values_match_v0102() {
        assert_eq!(
            AppSettingsKey::ClipboardRetention.as_str(),
            "clipboardRetentionDays"
        );
        assert_eq!(AppSettingsKey::SnippetsEnabled.as_str(), "snippetsEnabled");
        assert_eq!(AppSettingsKey::AiEnabled.as_str(), "aiEnabled");
        assert_eq!(
            AppSettingsKey::SearchScopes.as_str(),
            "launcherSearchScopes"
        );
    }

    #[test]
    fn all_settings_keys_match_v0102_raw_values() {
        const EXPECTED: &[&str] = &[
            "clipboardRetentionDays",
            "clipboardDisabledApps",
            "hyperKeyPhysicalKey",
            "hyperKeyIncludesShift",
            "hyperKeyQuickPress",
            "emojiSkinTone",
            "popToRootTimeout",
            "appearance",
            "compactMode",
            "showFavoritesInCompactMode",
            "launcherSearchScopes",
            "openOnCursorScreen",
            "autoSwitchInputSource",
            "paletteDraggable",
            "palettePosition",
            "fileSearchEnabled",
            "fileSearchScopes",
            "fileSearchIgnorePatterns",
            "notesEnabled",
            "customCommandsEnabled",
            "customCommandsShowInLauncher",
            "snippetsEnabled",
            "snippetsShowInLauncher",
            "windowManagementEnabled",
            "windowManagementShowInLauncher",
            "windowManagementGap",
            "windowManagementCycleOnRepeat",
            "quicklinksEnabled",
            "quicklinksShowInLauncher",
            "quicklinkOpensNewWindow",
            "quicklinkSelectionFallback",
            "quicklinkConfirmsBeforeDelete",
            "extensionsEnabled",
            "extensionsShowInLauncher",
            "extensionPackageManager",
            "extensionRegistries",
            "extensionCustomSearchPaths",
            "calendarEnabled",
            "calendarShowInLauncher",
            "joinWindowMinutes",
            "autoJoinMeetings",
            "autoJoinConfirms",
            "cameraPreview",
            "menuBarEvents",
            "menuBarLinkedEventsOnly",
            "hideCurrentEvent",
            "aiEnabled",
            "aiConnections",
            "aiDefaultModel",
            "aiWebSearch",
            "aiSystemPrompt",
            "aiSystemPromptEnabled",
            "aiRetentionDays",
            "aiOpensTo",
            "aiNewChatAfterMinutes",
            "quickActionsEnabled",
            "quickActionModel",
            "quickActionPreviews",
            "quickActionLanguage",
            "supportReminders",
        ];
        let actual: Vec<&str> = AppSettingsKey::ALL.iter().map(|k| k.as_str()).collect();
        assert_eq!(actual, EXPECTED);
        assert_eq!(
            AppSettingsKey::SearchScopes.as_str(),
            "launcherSearchScopes"
        );
        assert_eq!(AppSettingsKey::SnippetsEnabled.as_str(), "snippetsEnabled");
        assert_eq!(AppSettingsKey::AiEnabled.as_str(), "aiEnabled");
        assert_eq!(
            AppSettingsKey::ClipboardRetention.as_str(),
            "clipboardRetentionDays"
        );
        assert!(AppSettingsKey::ALL.contains(&AppSettingsKey::SearchScopes));
        assert!(AppSettingsKey::ALL.contains(&AppSettingsKey::SnippetsEnabled));
        assert!(AppSettingsKey::ALL.contains(&AppSettingsKey::AiEnabled));
        assert!(AppSettingsKey::ALL.contains(&AppSettingsKey::ClipboardRetention));
    }
}
